image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - deploy

variables:
  CONTAINER_DEV_IMAGE: smartcommunitylab/comuneintasca
  CONTAINER_DEV_TAG: $CI_COMMIT_SHORT_SHA
build:
  stage: build
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -t $CONTAINER_DEV_IMAGE:$CONTAINER_DEV_TAG -t $CONTAINER_DEV_IMAGE:latest .
    - docker push $CONTAINER_DEV_IMAGE:$CONTAINER_DEV_TAG
    - docker push $CONTAINER_DEV_IMAGE:latest

deploy:
  stage: deploy
  image: smartcommunitylab/kubectl-alpine:latest
  environment:
    name: platform-new
  script:
    - echo "deploy"
    - kubectl -n comuneintasca set image deployments/comuneintasca comuneintasca=$CONTAINER_DEV_IMAGE --record=true
    - kubectl -n comuneintasca rollout status deployment comuneintasca
  only:
    - master
