image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - deploy

variables:
  CONTAINER_DEV_IMAGE: smartcommunitylab/comuneintasca:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -t $CONTAINER_DEV_IMAGE .
    - docker push $CONTAINER_DEV_IMAGE

deploy:
  stage: deploy
  image: smartcommunitylab/kubectl-alpine:latest
  environment:
    name: develop
  script:
    - echo "deploy"
    - kubectl -n default set image deployments/comuneintasca comuneintasca=$CONTAINER_DEV_IMAGE --record=true
    - kubectl -n default rollout status deployment comuneintasca
  only:
    - master
